appName: cart

# Pod Security Policy
psp:
  enabled: false

containers:
  image:
    repo: robotshop/rs-cart
    tag: latest
    pullPolicy: ifNotPresent

  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 50Mi