appName: mysql

# Pod Security Policy
psp:
  enabled: false
  serviceAccountName: robot-shop

containers:
  image:
    repo: robotshop/rs-mysql
    tag: latest
    pullPolicy: ifNotPresent

  resources:
    limits:
      cpu: 200m
      memory: 100Mi
    requests:
      cpu: 100m
      memory: 50Mi

  runAs:
    user: 100
    group: {}

service:
  type: NodePort
  ports:
    name: http
    port: 8080
    targetPort: 8080