apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    service: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Values.appName }}
  template:
    metadata:
      labels:
        service: {{ .Values.appName }}
    spec:
      {{if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{end}}
      containers:
      - name: {{ .Values.appName }}
        image: {{ .Values.containers.image.repo }}:{{ .Values.containers.image.tag }}
        imagePullPolicy: {{ .Values.containers.image.pullPolicy }}
        # agent networking access
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: {{ .Values.containers.resources.limits.cpu }}
            memory: {{ .Values.containers.resources.limits.memory }}
          requests:
            cpu: {{ .Values.containers.resources.requests.cpu }}
            memory: {{ .Values.containers.resources.requests.memory }}
 