apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: {{ .Values.service.ports.name }}
    port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    service: {{ .Values.appName }}
    