apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
spec:
  selector:
    service: cart
  ports:
  - name: {{ .Values.ports.name }}
    port: {{ .Values.ports.port }}
    targetPort: {{ .Values.ports.targetPort }}
    